version: '3.3'
services:
  prometheus:
    build: ./monitoring/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
      - '--web.enable-admin-api'

  alertmanager:
    build: ./monitoring/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    ports:
      - 9093:9093
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter
    user: root
    networks:
      - monitor
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  blackbox-exporter:
    build: ./monitoring/blackbox-exporter
    command: '--config.file=/srv/blackbox.yml'
    networks:
      - monitor

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - 8080:8080
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=vasyansk
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitor

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.configs/prometheus
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.configs/grafana

networks:
  monitor:
